### ISSUE TITLE
Machine specific path, causing problem in catkin_make

### ISSUE THREAD

**Issue by yasharAhari** [TylerJulian/Cs4023#1]
https://github.com/TylerJulian/Cs4023/blob/d9ebe57f64d28252c99da9826825a8313937258c/robot_ws/src/CMakeCache.txt#L230

The CMakeCache.txt is not necessary for successful build. The CMake creates it for each machine on initial build to make it easier or faster for subsequent builds.  

Solution: Remove CMakeCache.txr from Repository.

**Comment by TylerJulian** [comment]
Removed CMakeCache.txt and added it to gitignore.
